LOW_GAS = 5
MAX_TYRES = 4
MIN_DEGRATATION = 94
KM_PER_LITER = 8

FINISHED = 0

TYRE_MAX_ENDURANCE = PERCENTAGE = 100
TYRE_DEGRADATION_PER_KM = 1/3
TYRE_DISTANCE_ENDURANCE = 3
TYRE_MAX_ENDURANCE_DISTANCE = 300
TYRE_MIN_ENDURANCE_DISTANCE = 15

BASE_URL = 'http://localhost:8000/api/v1/cars'
